version: "3.8"

services:

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
    depends_on:
      - grocy-database-service

  grocy-database-service:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: 989878
      MYSQL_DATABASE: GROCERY
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
